version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: legalrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.21.8
    ports:
      - "8081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - t2v-transformers

  # Sentence Transformers
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0

  # Legal RAG Agent API + Frontend
  legal-rag-api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/legalrag
      
      # Redis
      REDIS_URL: redis://redis:6379
      
      # Weaviate
      WEAVIATE_URL: http://weaviate:8080
      
      # API Keys
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Vertex AI
      VERTEX_AI_PROJECT_ID: ${VERTEX_AI_PROJECT_ID}
      VERTEX_AI_LOCATION: ${VERTEX_AI_LOCATION:-us-central1}
      VERTEX_AI_MODEL: ${VERTEX_AI_MODEL:-gemini-2.5-pro}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/gcp-credentials.json
      
      # App Settings
      APP_NAME: Legal RAG Agent
      APP_VERSION: 1.0.0
      DEBUG: true
      API_V1_PREFIX: /api/v1
      
      # File Upload
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 52428800  # 50MB
      ALLOWED_EXTENSIONS: '[".pdf", ".docx", ".txt", ".rtf"]'
    volumes:
      - ./app:/app/app
      - upload_data:/app/uploads
      - ./app/static:/app/app/static
      - ./credentials:/app/credentials
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      weaviate:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 10 &&
        echo 'Starting Legal RAG Agent...' &&
        python -m uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Celery Worker for document processing
  celery-worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/legalrag
      
      # Redis
      REDIS_URL: redis://redis:6379
      
      # Weaviate
      WEAVIATE_URL: http://weaviate:8080
      
      # API Keys
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Vertex AI
      VERTEX_AI_PROJECT_ID: ${VERTEX_AI_PROJECT_ID}
      VERTEX_AI_LOCATION: ${VERTEX_AI_LOCATION:-us-central1}
      VERTEX_AI_MODEL: ${VERTEX_AI_MODEL:-gemini-2.5-pro}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/gcp-credentials.json
      
      # App Settings
      APP_NAME: Legal RAG Agent
      APP_VERSION: 1.0.0
      DEBUG: true
      
      # File Upload
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 52428800  # 50MB
      ALLOWED_EXTENSIONS: '[".pdf", ".docx", ".txt", ".rtf"]'
    volumes:
      - ./app:/app/app
      - upload_data:/app/uploads
      - ./app/static:/app/app/static
      - ./credentials:/app/credentials
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Starting Celery Worker...' &&
        cd /app &&
        python -m celery -A app.workers.simple_worker worker --loglevel=info --concurrency=2
      "

volumes:
  postgres_data:
  redis_data:
  weaviate_data:
  upload_data: 